<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hsmail"
 *
 * Auto generated by Extension Builder 2021-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Hsmail',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Usman Ahmad',
    'author_email' => 'ua@onm.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.0.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
