<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hsmail"
 *
 * Auto generated by Extension Builder 2021-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'hotelsuite MAIL',
    'description' => 'hotelsuite MAIL (hs MAIL) enables you to load (registration) forms from the hotelsuite MAIL e-mail marketing system (https://www.hotelsuite.de) and to display them in the frontend of your website. - Get in touch with us: Open New Media GmbH | Digital communication agency | Tel .: +49 261 30380-80 | E-Mail: info@onm.de | Web: https://www.onm.de | Hotel solutions: https://www.hotelsuite.de',
    'category' => 'plugin',
    'author' => 'Usman Ahmad, Tobias Gräber',
    'author_email' => 'ua@onm.de, tg@onm.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.1.3',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.0.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
